<a href="https://colab.research.google.com/github/hunter198333/Digitrades/blob/main_ai_trader_agent/Trading_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You can install Python libraries using the `pip` package installer. For example, to install a library like `numpy`, you would run the following command in a code cell:

```bash
!pip install numpy
```

The `!` before `pip` allows you to run shell commands directly in the Colab notebook. If the library is already installed, `pip` will tell you that the requirement is already satisfied. If you need to install a specific version, you can specify it like this: `!pip install numpy==1.20.0`.

Here's an example:

In [2]:
%pip install numpy

Requirement already satisfied: numpy in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import kagglehub
path = kagglehub.dataset_download("borismarjanovic/price-volume-data-for-all-us-stocks-etfs")

c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\geoff\.cache\kagglehub\datasets\borismarjanovic\price-volume-data-for-all-us-stocks-etfs\3.archive...

100%|██████████| 492M/492M [00:08<00:00, 59.0MB/s]

Extracting files...

In [ ]:
# Install numpy
%pip install numpy

# Verify installation by importing and checking version
import numpy as np
print(f"NumPy version: {np.__version__}")

Requirement already satisfied: numpy in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.3)
NumPy version: 2.5.3

In [ ]:
# Install pandas
%pip install pandas

# Verify installation
import pandas as pd
print(f"Pandas version: {pd.__version__}")

Requirement already satisfied: pandas in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\geoff\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\geoff\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Pandas version: 3.0.5

In [ ]:
# Install yfinance library to fetch financial data
%pip install yfinance

Requirement already satisfied: yfinance in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (3.0.5)
Requirement already satisfied: peewee>=3.16.2 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (4.5.1)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\geoff\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.11.8)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (7.36.1)
Requirement already satisfied: pytz>=2022.5 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (2.34.2)
Requirement already satisfied: websockets>=13.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\geoff\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.3.0->yfinance) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\geoff\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests>=2.31->yfinance) (2.7.0)

In [7]:
import yfinance as yf
import pandas as pd

# Define the ticker for Bitcoin (BTC-USD) and download daily data
btc_ticker = yf.Ticker("BTC-USD")
btc_data = btc_ticker.history(period="max", interval="1d")

# Display the first 5 rows of the downloaded data
print("Bitcoin daily data:")
display(btc_data.head())

Bitcoin daily data:

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0
2014-09-18 00:00:00+00:00,456.859985,456.859985,413.104004,424.440002,34483200,0.0,0.0
2014-09-19 00:00:00+00:00,424.102997,427.834991,384.532013,394.795990,37919700,0.0,0.0
2014-09-20 00:00:00+00:00,394.673004,423.295990,389.882996,408.903992,36863600,0.0,0.0
2014-09-21 00:00:00+00:00,408.084991,412.425995,393.181000,398.821014,26580100,0.0,0.0

In [8]:
# Calculate the 50-day Simple Moving Average (SMA)
btc_data['SMA_50'] = btc_data['Close'].rolling(window=50).mean()

print("Bitcoin daily data with 50-day SMA:")
display(btc_data.tail())

Bitcoin daily data with 50-day SMA:

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_50
Date,,,,,,,,
2026-09-11 00:00:00+00:00,76559.125000,79818.335938,76162.914062,77173.796875,37410998193,0.0,0.0,70645.507656
2026-09-12 00:00:00+00:00,77175.070312,77479.656250,77045.000000,77270.468750,12664765797,0.0,0.0,70908.947109
2026-09-13 00:00:00+00:00,77270.179688,77415.656250,76498.382812,76838.156250,13607872549,0.0,0.0,71159.473984
2026-09-14 00:00:00+00:00,76830.281250,79568.953125,76367.375000,78163.382812,29909358382,0.0,0.0,71415.935625
2026-09-15 00:00:00+00:00,78181.328125,78232.375000,74984.843750,75598.101562,39443406848,0.0,0.0,71653.399688

In [9]:
# Calculate the 20-day Exponential Moving Average (EMA)
btc_data['EMA_20'] = btc_data['Close'].ewm(span=20, adjust=False).mean()

print("Bitcoin daily data with 50-day SMA and 20-day EMA:")
display(btc_data.tail())

Bitcoin daily data with 50-day SMA and 20-day EMA:

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_50,EMA_20
Date,,,,,,,,,
2026-09-11 00:00:00+00:00,76559.125000,79818.335938,76162.914062,77173.796875,37410998193,0.0,0.0,70645.507656,77000.658091
2026-09-12 00:00:00+00:00,77175.070312,77479.656250,77045.000000,77270.468750,12664765797,0.0,0.0,70908.947109,77026.354344
2026-09-13 00:00:00+00:00,77270.179688,77415.656250,76498.382812,76838.156250,13607872549,0.0,0.0,71159.473984,77008.430716
2026-09-14 00:00:00+00:00,76830.281250,79568.953125,76367.375000,78163.382812,29909358382,0.0,0.0,71415.935625,77118.426154
2026-09-15 00:00:00+00:00,78181.328125,78232.375000,74984.843750,75598.101562,39443406848,0.0,0.0,71653.399688,76973.633335

### Define Buy and Sell Signals

We will define buy and sell signals based on the crossover strategy of the `EMA_20` and `SMA_50`:

*   **Buy Signal**: `EMA_20` crosses above `SMA_50`.
*   **Sell Signal**: `EMA_20` crosses below `SMA_50`.

In [10]:
import yfinance as yf
import pandas as pd

# Define the ticker for Bitcoin (BTC-USD) and download daily data
btc_ticker = yf.Ticker("BTC-USD")
btc_data = btc_ticker.history(period="max", interval="1d")

# Calculate the 50-day Simple Moving Average (SMA)
btc_data['SMA_50'] = btc_data['Close'].rolling(window=50).mean()

# Calculate the 20-day Exponential Moving Average (EMA)
btc_data['EMA_20'] = btc_data['Close'].ewm(span=20, adjust=False).mean()

# Create a 'Signal' column, initialized to 0 (no signal)
btc_data['Signal'] = 0.0

# Generate Buy signals (1.0) when EMA_20 crosses above SMA_50
# This means EMA_20 was below SMA_50 in the previous period and is now above it.
btc_data.loc[btc_data['EMA_20'] > btc_data['SMA_50'], 'Signal'] = 1.0

# Generate Sell signals (-1.0) when EMA_20 crosses below SMA_50
# This means EMA_20 was above SMA_50 in the previous period and is now below it.
btc_data.loc[btc_data['EMA_20'] < btc_data['SMA_50'], 'Signal'] = -1.0

# To detect actual crossovers, we look for the change in signal.
# A buy signal happens when the signal changes from -1.0 to 1.0 (or 0.0 to 1.0 if not already -1.0)
# A sell signal happens when the signal changes from 1.0 to -1.0 (or 0.0 to -1.0 if not already 1.0)

# Calculate the difference to find the actual crossover points
btc_data['Position'] = btc_data['Signal'].diff()

print("Bitcoin daily data with Buy/Sell Signals:")
display(btc_data[btc_data['Position'] != 0].head(10))

Bitcoin daily data with Buy/Sell Signals:

,Open,High,Low,Close,Volume,Dividends,Stock Splits,SMA_50,EMA_20,Signal,Position
Date,,,,,,,,,,,
2014-09-17 00:00:00+00:00,465.864014,468.174011,452.421997,457.334015,21056800,0.0,0.0,NaN,457.334015,0.0,NaN
2014-11-05 00:00:00+00:00,330.683014,343.368988,330.683014,339.485992,19817200,0.0,0.0,372.766840,349.705580,-1.0,-1.0
2014-11-13 00:00:00+00:00,427.273010,457.092987,401.122986,420.734985,58945000,0.0,0.0,365.445421,365.672494,1.0,2.0
2014-12-14 00:00:00+00:00,346.726990,353.316010,345.417999,351.631989,12415200,0.0,0.0,363.239580,362.396580,-1.0,-2.0
2015-02-25 00:00:00+00:00,238.889999,239.339996,235.529999,237.470001,11496200,0.0,0.0,235.776460,236.696480,1.0,2.0
2015-03-31 00:00:00+00:00,247.453995,248.729996,242.738998,244.223999,22672000,0.0,0.0,257.332741,257.305157,-1.0,-2.0
2015-05-22 00:00:00+00:00,235.320999,240.968994,235.059998,240.348007,27003000,0.0,0.0,235.640061,236.228191,1.0,2.0
2015-06-03 00:00:00+00:00,225.735992,227.404007,223.929993,225.873993,17752400,0.0,0.0,233.349380,233.179613,-1.0,-2.0
2015-06-18 00:00:00+00:00,249.427994,252.108002,244.126999,249.007004,30980200,0.0,0.0,235.068240,235.884650,1.0,2.0
2015-08-13 00:00:00+00:00,266.183014,266.231995,262.841003,264.079987,27685500,0.0,0.0,274.702038,274.620324,-1.0,-2.0

In [1]:
%pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (26.3)
Collecting pyyaml (from kagglehub)
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (2.34.2)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: protobuf in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.36.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2026.7.22)
Requirement already satisfied: colorama in c:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, pyyaml, kagglesdk, kagglehub

   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   ---------------------------------------- 4/4 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37 pyyaml-6.0.3 tqdm-4.70.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tqdm.exe is installed in 'C:\Users\geoff\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.